basket/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
app_name = 'basket'
urlpatterns=[
    path('',views.basket_summary,name='basket_summary'),
    path('add/',views.basket_add,name='basket_add'),
    path('basket_delete',views.basket_delete,name='basket_delete')

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

basketballshop/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from account import views as accountview
from payment.views import mpesa_callback
from dashboard.views import dashboard
urlpatterns = [
   
    path('admin/', admin.site.urls),

    path('login/',accountview.login_view,name='login'),
    path("account/",accountview.account,name="account"),
    path('logout/',accountview.logout_view,name='logout'),
    path('signup/',accountview.signup_view,name='signup'),
    path('basket/',include('basket.urls',namespace='basket')),
    path("",include('mainpage.urls',namespace='mainpage')),
    path("checkout/",include("order.urls",namespace="order")),
    path("mpesacall/",mpesa_callback,name="mpesa"),
    path("dashboard/",dashboard)
    
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mainpage/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
app_name = 'mainpage'
urlpatterns=[
    path('',views.home,name="home"),
    
    path('single/<slug>/',views.singleproduct,name='single'),
    path('faq/',views.faq,name='faq'),
    path('allproduct/',views.allproducts,name='allproducts'),
    path('search/',views.search,name="search"),
    path('filter/<filtername>/',views.filter,name="product_filter")

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

order/urls.py
from django.conf import settings
from django.urls import path
from django.conf.urls.static import static
from .views import checkout,add,track
app_name="order"

urlpatterns=[
    path("",checkout,name="checkout"),
    path("add/",add,name="add"),
    path("success/",add,name="success"),
    path("track/",track,name="track"),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

order/models.py
from django.db import models
from decimal import Decimal
from django.conf import settings
from django.db import models
from base.models import Product


class Order(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='order_user')
    #full_name=models.CharField(max_length=50)
    #town=models.CharField(max_length=250)
    #phone=models.CharField(max_length=14)
    #post_code=models.CharField(max_length=50)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    total_paid=models.IntegerField()
    order_key=models.CharField(max_length=250)
    order_status=models.CharField(max_length=25)
    payment_status=models.BooleanField(default=False)
    voucher_code=models.CharField(max_length=250)

    class Meta():
        ordering=('-created',)
    def __str__(self):
        return str(self.order_key)    


class OrderItem(models.Model):
    order=models.ForeignKey(Order,related_name='items',on_delete=models.CASCADE)
    product=models.ForeignKey(Product,related_name='order_items',on_delete=models.CASCADE)
    price=models.IntegerField()
    quantity=models.PositiveIntegerField(default=1)
    def __str__(self):
        return str(self.order)

class OrderShipping(models.Model):
    tracking_id=models.CharField(max_length=50)
    shipping_date=models.DateField(auto_now_add=True)
    order_id=models.ForeignKey(Order,related_name="ordershipping",on_delete=models.CASCADE)
    shipping_method=models.CharField(max_length=50)
    shipping_fee=models.CharField(max_length=20)
    order_key=models.CharField(max_length=10)

order/views.py
from django.shortcuts import render,redirect,HttpResponse
from basket.basket import Basket
from order.models import Order,OrderItem
from account.forms import Addressform
from django.http import JsonResponse
from account.models import shipping
from django.db import transaction,IntegrityError
from payment import mpesa_payment
from base.models import Product
import random,string 
# Create your views here
#.
def checkout(request):
    context={}
    if request.user.is_authenticated:
        basket=Basket(request)
        if request.POST:
            form=Addressform(request.POST)
            context['item']=basket.__len__()
        else:
            form=Addressform()
            context['addressform']=form
            context['item']=basket.__len__()    
        return render(request,"order/checkout.html",context)
    else:    
        return redirect('login')
@transaction.non_atomic_requests
def add(request):
    basket=Basket(request)
    user_id=request.user.id
    baskettotal=basket.get_total_price()     
    
    if 'mpesa' in request.POST:
        form=Addressform(request.POST)
        if form.is_valid():
            mpesa=mpesa_payment.mpesa()
            order_key=mpesa.simulate_customer_to_account(254708073370,10)
            print(order_key)
            fullname=form.cleaned_data['fullnames']
            county=form.cleaned_data['county']
            city=form.cleaned_data['city']
            area=form.cleaned_data['area']
            email=form.cleaned_data['email']
            phone=form.cleaned_data['phone_number']
            try:
                address=shipping.objects.create(fullnames=fullname,county=county,city=city,area=area,email=email,phone_number=phone,user=request.user)
                #order section
                order=Order.objects.create(user=request.user,total_paid=float(basket.get_total_price()),order_key=order_key,order_status="created",payment_status=False,voucher_code=False)
                #order_id=order.pk
                for item in basket:
                    OrderItem.objects.create(order=order,product=item['product'],price=item['price'],quantity=item['qty'])
                response=JsonResponse({'success':'Order Created'})  
                return render(request,"order/success.html")
            except:
                return render(request,"order/fail.html")    
        else:
            redirect("checkout")
    elif 'delivery' in request.POST:
        #will handle the user pay on delivery
        order_key=''.join(random.SystemRandom().choice(string.ascii_letters + string.digits) for _ in range(10))
        if Order.objects.filter(order_key=order_key).exists():
            pass
        else:
            form=Addressform(request.POST)
            if form.is_valid():
                fullname=form.cleaned_data['fullnames']
                county=form.cleaned_data['county']
                city=form.cleaned_data['city']
                area=form.cleaned_data['area']
                email=form.cleaned_data['email']
                phone=form.cleaned_data['phone_number']
                try:
                    address=shipping.objects.create(fullnames=fullname,county=county,city=city,area=area,email=email,phone_number=phone,user=request.user)
                    #order section
                    order=Order.objects.create(user=request.user,total_paid=float(basket.get_total_price()),order_key=order_key,order_status="created",payment_status=False,voucher_code=False)
                    #order_id=order.pk
                    for item in basket:
                        OrderItem.objects.create(order=order,product=item['product'],price=item['price'],quantity=item['qty'])
                        product=Product.objects.filter(id=item['product'].id)
                        for p in product:
                            p.stock=(p.stock-item['qty'])
                            p.save()
                    response=JsonResponse({'success':'Order Created'})  
                    return render(request,"order/success.html")
                except IntegrityError:

                    return render(request,"order/fail.html",{'prod':p})
                    
                except Exception as e:
                    print(repr(e))
                    return render(request,"order/fail.html")  
                
            else:
                return HttpResponse("Form is invalid")    
    else:
        pass   
def track(request):
    return render(request,"order/track.html")        
    r#eturn HttpResponse("hello")

templates/order/checkout.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Checkout</title>
    <link rel="stylesheet" href="{% static 'materialize.min.css'%}">
   <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.0.7/css/swiper.min.css">-->
    <link rel="stylesheet" href="{% static 'checkout.css' %}">

    


</head>
<body>
    <div id="app" v-cloak>
     
        <div class="container wrapper">
          <div class="row hide-on-med-and-up" v-cloak>
            <div class="col s12 m6">
              <div class="card">
                <div class="card-content">
                  <p><b>Items in cart:</b> 25</p>
                  <p><b>Shipping:</b> mango - $120</p>
                  <p><b>Total:</b> $150</p>
                  <span class="small-text grey-text text-darken-2 m-top-10 ">Fill out the information below and go directly to payment by clicking the button.</span>
                </div>
                <a v-on:click="scrollToBottom();" class="btn-floating halfway-fab waves-effect waves-light red"><i class="material-icons">arrow_downward
      </i></a>
              </div>
      
            </div>
          </div>
          <div class="row">
            <div class="col s12 m6">
              <div class="card" id="step-1">
                <div class="card-content">
                  <span class="card-title activator grey-text text-darken-4"><b>Information</b></span>
                  <div class="row m-top-15">
                    <form class="col s12" action="{%url 'order:add'%}" method="POST">
                      {%csrf_token%}
                      {% for field in addressform %}
                         <div class="row">
                        <div class="input-field col s12 l6 m-top-15">
                          {{field}}
                        </div>
                        
                      </div>
                      {% endfor %}
                            <label class="d-block m-top-15">
                        <input type="checkbox" v-model="showAlternative" class="filled-in" />
                        <span>Save for future</span>
                      </label>
            
                     
                    
                  </div>
                </div>
              </div>
              <div class="card" id="step-2" v-cloak>
                <div class="card-content">
                  <span class="card-title activator grey-text text-darken-4"><b>Shipping</b></span>
                  <p>Please choose your desired shipping provider.</p>
                  <!--<form action="#">
                    <p class="p-top-10" v-for="(shippingMethod, index) in shippingMethods">
                      <label>
                        <input v-model="shipping" name="group1" :value="shippingMethod.id" type="radio" :id="shippingMethod.id" class="with-gap m-top-15" />
                        <span>pickup - $120</span>
                      </label>
                      
                    </p>
                    <p class="p-top-10" v-for="(shippingMethod, index) in shippingMethods">
                      <label>
                        <input v-model="shipping" name="group1" :value="shippingMethod.id" type="radio" :id="shippingMethod.id" class="with-gap m-top-15" />
                        <span>pickup - $120</span>
                      </label>
                      
                    </p>
                    <p class="p-top-10" v-for="(shippingMethod, index) in shippingMethods">
                      <label>
                        <input v-model="shipping" name="group1" :value="shippingMethod.id" type="radio" :id="shippingMethod.id" class="with-gap m-top-15" />
                        <span>pickup - $120</span>
                      </label>
                      
                    </p>
                  </form>-->
                  <span class="card-title activator grey-text text-darken-4 m-top-15 p-top-10"><b>Voucher</b></span>
                  <label v-if="!showVoucher" class="d-block m-top-15">
                        <input type="checkbox" v-model="showVoucher" class="filled-in" />
                        <span>I have a voucher code</span>
                      </label>
                  <div v-if="showVoucher" class="row m-top-10 p-top-10">
                    <div class="input-field col s12 l6">
                      <input id="voucher" type="text" class="validate" placeholder="E.g #1254454454">
                      
                    </div>
                    <div class="col s12 l6">
                      <a class="waves-effect waves-light btn indigo darken-4 m-top-10">Add voucher</a>
                    </div>
      
                  </div>
                </div>
              </div>

            </div>
            <div class="col s12 m6">
              <div class="card" id="step-4" v-cloak>
                <div class="card-content">
                  <span class="card-title activator grey-text text-darken-4"><b>Order summary</b></span>
                  <div class="row info">
                    <div class="col s12 m6">
                      <p><b>Billing address:</b></p>
                      <p>mango</p>
                      <p>{{ company }}</p>
                      <p>{{ addressComputed }}</p>
                      <p>{{ cityComputed }}</p>
                      <p>{{ email }}</p>
                      <p>{{ phone }}</p>
                    </div>
                    <div class="col s12 m6" v-if="showAlternative">
                      <p><b>Delivery address:</b></p>
                      <p>{{ delName }}</p>
                      <p>{{ delCompany }}</p>
                      <p>{{ delAddressComputed }}</p>
                      <p>{{ delCityComputed }}</p>
                    </div>
                  </div>
                  <span class="card-title activator grey-text text-darken-4 m-top-15"><b>Your order</b></span>
                  <span><b>
                  {{item}}
                  
                   Items</b></span>
                  <ul class="collection">
                  {% for item in basket %}
                  {% with product=item.product %}
                  
                  
                    <li class="collection-item avatar" id="sepic" data-index="{{product.id}}">
                      <img src="{{MEDIA_URL}}{{product.product_image}}" alt="" class="circle">
                      <div class="row">
                        <div class="col s12 l4">
                          <span class="title">{{product.product_name}}</span>
                          <p>KES {{product.product_price}}</p>
                        </div>
                      </div>
                      <a href="#" id="{{product.id}}" class="btn-remove secondary-content"><i class="material-icons">clear</i></a>
                    </li>
                    {% endwith %}
                  {% endfor %}
                    
                    
                      
                      
                      
                  </ul>
                  <ul>
                    <li v-if="shipping">
                      <span><b>Shipping</b> <i>Pickup</i></span>
                      <span class="right">KES {{basket.get_total_price}}</span>
                    </li>
                    <li v-if="taxTotal">
                      <span><b>TAX</b></span>
                      <span class="right">$20</span>
                    </li>
                  </ul>
                </div>
                <div class="card-action" v-if="basketTotal">
                  <span><b>Total</b></span>
                  <span class="right"><b>KES {{basket.get_total_price}}</b></span>
                </div>
                <div class="card-action">
                  <span class="card-title activator grey-text text-darken-4"><b>Payment</b></span>
                  <p class="payment-info">Please choose your desired payment method. Credit card option will redirect you to the payment gateway.</p>
                  <p>
                    <label>
                        <input type="checkbox"  class="filled-in" />
                        <span>Please sign me up for the newsletter</span>
                    </label></p>
                  <p>
                    <label>
                        <input type="checkbox" v-model="consent" class="filled-in" />
                        <span>I hereby confirm that the information that I have provided is correct and that I accept the <a href="#" class="indigo-text text-darken-4">Terms and Conditions</a></span>
                    </label></p>
                  <button type="submit" class="waves-effect waves-light btn-large" name="mpesa">
                  Mpesa
                  </button>
                  <button type="submit" class="waves-effect waves-light btn-large" name="delivery">Mpesa On DeliverY</button>
                  <a ref="link"  href="https://payment.quickpay.net/payments/a4d5e59b2695e3b5c2d8b19c8112835a5e0c3365e0782a4fb7b43091b5142af9" class="waves-effect waves-light btn-credit-card blue-grey"><i class="material-icons left">credit_card</i>Pay with Credit Card</a>
                </div>
               
              </div>

            </div>
          </div>
           </form>
        </div>
      </div>
      <script src="{% static 'jquery.min.js' %}"></script>
      <script>
      $(document).on('click','.btn-remove',function(e){
               
    e.preventDefault();
    prodid=$(this).attr('id')
    
    $.ajax({
        type:'POST',
        url: '{% url "basket:basket_delete" %}',
        data:{
            productid:prodid,
            csrfmiddlewaretoken: "{{csrf_token}}",
            action:'post'
        
    },
    success:function(json){
        $("#checkout_items").text(json.test)
        $('#sepic[data-index="'+prodid+'"]').remove();
        window.location.href=window.location.href
        
    },
    error: function(xhr,errmsg,err){}
}); })
      </script>
</body>
</html>

templates/order/fail.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}
    Fail
{% endblock title %}

{% block content %}
    <div class="page-wrapper" style="margin-top: 140px; height:100vh;"  >
            <!-- End .header -->
        <div class="background"></div>
<div class="container">
	
	<!--/.row-->
	<div class="row" style="margin-top:120px;">
		<div class="modalbox error col-sm-8 col-md-6 col-lg-5 center animate">
			<div class="icon">
				<span class="fa fa-times" style="margin-top:30%;font-size:40px;"></span>
			</div>
			<!--/.icon-->
			<h1>Oh no!</h1>
			{%if prod%}
			<p>The {{prod}} stock is less than your order ,
				<br> you should try again with reduced order.</p>
			{%else%}
			<p>Something went wrong  ,
				<br> you should try again.</p>
			{%endif%}	
			<a href="{%url 'order:checkout'%}"><button type="button" class="redo btn">Try again</button></a>
			<span class="change">-- Try again Later --</span>
		</div>
		<!--/.success-->
	</div>
	<!--/.row-->
</div>
<!--/.container-->
            <!-- End .main -->
    
            <!-- End .footer -->
        </div>
{% endblock content %}

templates/order/success.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}
    Success
{% endblock title %}

{% block content %}
    <div class="page-wrapper" style="margin-top: 140px; height:100vh;"  >
            <!-- End .header -->
        <div class="background"></div>
<div class="container">
	<div class="row" style="margin-top:120px;">
		<div class="modalbox success col-sm-8 col-md-6 col-lg-5 center animate">
			<div class="icon">
				<span class="fa fa-check" style="margin-top:30%;font-size:40px;"></span>
			</div>
			<!--/.icon-->
			<h1>Success!</h1>
			<p>We've sent a confirmation to your e-mail
				<br>for verification.</p>
			<a href="{%url 'mainpage:home'%}"><button type="button" class="redo btn">Ok</button></a>
			<span class="change">-- Click to see opposite state --</span>
		</div>
		<!--/.success-->
	</div>
	<!--/.row-->
	<div class="row">
		<div class="modalbox error col-sm-8 col-md-6 col-lg-5 center animate" style="display: none;">
			<div class="icon">
				<span class="glyphicon glyphicon-thumbs-down"></span>
			</div>
			<!--/.icon-->
			<h1>Oh no!</h1>
			<p>Oops! Something went wrong,
				<br> you should try again.</p>
			<button type="button" class="redo btn">Try again</button>
			<span class="change">-- Click to see opposite state --</span>
		</div>
		<!--/.success-->
	</div>
	<!--/.row-->
</div>
<!--/.container-->
            <!-- End .main -->
    
            <!-- End .footer -->
        </div>
{% endblock content %}

templates/order/track.html
{% extends 'base/base.html'%}
{% block title %}
Tracking
{% endblock title %}
{%block content%}
<div class="tracking">
                <!--Tracking product start-->
    <div class="tracking-product mt-60 mb-60">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-8 text-center">
                    <h2>Your Tracking Number</h2>
                    <form action="#">
                        <input type="text" placeholder="Eg:#0.325FHJU658745EGU" required>
                        <button type="submit"><i class="fa fa-binoculars"></i> Track now</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!--Tracking product end-->

    <!--Tracking product start-->
    <div class="feature-area  mt-60">
        <div class="container">
          
        
            <div class="row justify-content-center">
            <p>To Track an order Enter the Tracking code sent to you via email and Text</p>
            <!--
            
                <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12">
                    <div class="single-feature-2 bottom-after">
                        <i class="fa fa-bullhorn " ></i>
                        <h4>Seller Shipped Your order</h4>
                        <p>Certainty listening no no behaviour existence assurance situation is. Because add why</p>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12">
                    <div class="single-feature-2 bottom-before">
                        <div class="animation">
                            <i class="fa fa-paper-plane"></i>
                        </div>
                        <h4>Depert from original Country</h4>
                        <p>Certainty listening no no behaviour existence assurance situation is. Because add why</p>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12">
                    <div class="single-feature-2 bottom-after disabled">
                        <i class="fa fa-plane"></i>
                        <h4>Arrived at destination country</h4>
                        <p>Certainty listening no no behaviour existence assurance situation is. Because add why</p>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12">
                    <div class="single-feature-2 disabled">
                        <i class="fa fa-gift"></i>
                        <h4>Product Delivered</h4>
                        <p>Certainty listening no no behaviour existence assurance situation is. Because add why</p>
                    </div>
                </div>-->
            </div>
        </div>
  

    </div>

    <!--Tracking product end-->
        </div>
        
        {%endblock%}