basket/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
app_name = 'basket'
urlpatterns=[
    path('',views.basket_summary,name='basket_summary'),
    path('add/',views.basket_add,name='basket_add'),
    path('basket_delete',views.basket_delete,name='basket_delete')

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

basketballshop/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from account import views as accountview
from payment.views import mpesa_callback
from dashboard.views import dashboard
urlpatterns = [
   
    path('admin/', admin.site.urls),

    path('login/',accountview.login_view,name='login'),
    path("account/",accountview.account,name="account"),
    path('logout/',accountview.logout_view,name='logout'),
    path('signup/',accountview.signup_view,name='signup'),
    path('basket/',include('basket.urls',namespace='basket')),
    path("",include('mainpage.urls',namespace='mainpage')),
    path("checkout/",include("order.urls",namespace="order")),
    path("mpesacall/",mpesa_callback,name="mpesa"),
    path("dashboard/",dashboard)
    
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mainpage/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
app_name = 'mainpage'
urlpatterns=[
    path('',views.home,name="home"),
    
    path('single/<slug>/',views.singleproduct,name='single'),
    path('faq/',views.faq,name='faq'),
    path('allproduct/',views.allproducts,name='allproducts'),
    path('search/',views.search,name="search"),
    path('filter/<filtername>/',views.filter,name="product_filter")

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

order/urls.py
from django.conf import settings
from django.urls import path
from django.conf.urls.static import static
from .views import checkout,add,track
app_name="order"

urlpatterns=[
    path("",checkout,name="checkout"),
    path("add/",add,name="add"),
    path("success/",add,name="success"),
    path("track/",track,name="track"),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mainpage/models.py
from django.db import models

# Create your models here.

mainpage/views.py
from django.shortcuts import render,redirect,HttpResponse
from base.models import Product,Category
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
# Create your views here.
def home(requests):
    products=Product.objects.all()[0:4]
    new_products=Product.objects.all().filter(is_new=True).order_by('?') & Product.objects.all().filter(stock__gte=1)[0:3]
    return render(requests,'mainpage/home.html',{'products':products,'new_products':new_products})
    
def singleproduct(requests,slug):
    singleproduct=Product.objects.all().filter(product_slug=slug)    

    return render(requests,'mainpage/single_product.html',{'products':singleproduct})
def faq(request):
    return render(request,'mainpage/faq.html')   
def allproducts(request):
    page=request.GET.get('page',1)
    product=Product.objects.all().filter(stock__gte=1)
    paginator=Paginator(product,12)
    categories=Category.objects.all()
    try:
        product_page=paginator.page(page)
    except PageNotAnInteger:
        product_page=paginator.page(1)
    except EmptyPage:
        product_page=paginator.page(paginator.num_pages)    
    print(categories)    
    return render(request,'mainpage/allproducts.html',{'products':product_page,'categories':categories})     
def search(request):
    
    searchword=request.GET.get('searchword') 
    product=Product.objects.filter(product_name__icontains=searchword) & Product.objects.all().filter(stock__gte=1)
   
    return render(request,'mainpage/allproducts.html',{'products':product})     
def filter(request,filtername):
    if filtername=="lowest":
        page=request.GET.get('page',1)
        product=Product.objects.all().filter(stock__gte=1).order_by("product_price")
        paginator=Paginator(product,12)
        categories=Category.objects.all()
        try:
            product_page=paginator.page(page)
        except PageNotAnInteger:
            product_page=paginator.page(1)
        except EmptyPage:
            product_page=paginator.page(paginator.num_pages)    
        print(categories)    
        return render(request,'mainpage/allproducts.html',{'products':product_page,'categories':categories})  
    elif filtername=='highest':
        page=request.GET.get('page',1)
        product=Product.objects.all().order_by("-product_price")
        paginator=Paginator(product,12)
        categories=Category.objects.all()
        try:
            product_page=paginator.page(page)
        except PageNotAnInteger:
            product_page=paginator.page(1)
        except EmptyPage:
            product_page=paginator.page(paginator.num_pages)    
        print(categories)    
        return render(request,'mainpage/allproducts.html',{'products':product_page,'categories':categories})  
    else:
        page=request.GET.get('page',1)
        product=Product.objects.filter(category=filtername)
        paginator=Paginator(product,12)
        categories=Category.objects.all()
        try:
            product_page=paginator.page(page)
        except PageNotAnInteger:
            product_page=paginator.page(1)
        except EmptyPage:
            product_page=paginator.page(paginator.num_pages)    
        print(categories)    
        return render(request,'mainpage/allproducts.html',{'products':product_page,'categories':categories})      

templates/mainpage/allproducts.html
{% extends "base/base.html" %}

{% block title %}
    All Products
{% endblock title %}    

{% block content %}
    <div class="product-view" style="margin-top:120px;">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-14">
                <div class="row">
                    <div class="col-md-12">
                        <div class="product-view-top">
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="product-search">
                                    <form action="{% url 'mainpage:search' %}">
                                        <input type="Text" Placeholder="Search" name='searchword' AUTOCOMPLETE="OFF">
                                        <button><i class="fa fa-search"></i></button>
                                    </form>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="product-short">
                                        <div class="dropdown">
                                            <div class="dropdown-toggle one" data-toggle="dropdown">Product short by</div>
                                            <div class="dropdown-menu dropdown-menu-right">
                                            {% for category in categories %}
                                                <a href="{%url 'mainpage:product_filter' filtername=category.id%}" class="dropdown-item">{{category.category_name}}</a>
                                            {% endfor %}
                                                
                                                
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="product-price-range">
                                        <div class="dropdown">
                                            <div class="dropdown-toggle" data-toggle="dropdown">Product price range</div>
                                            <div class="dropdown-menu dropdown-menu-right">
                                                <a href="{%url 'mainpage:product_filter' filtername='lowest' %}" class="dropdown-item">Lowest Price-Highest</a>
                                                <a href="{% url 'mainpage:product_filter' filtername='highest' %}" class="dropdown-item">Highest Price-Lowest</a>

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% for product in products %}
                        <div class="col-lg-2 col-md-6 col-12">
    <!-- Start Single Product -->
    <div class="single-product">
        <div class="product-image">
            <img src="{{MEDIA_URL}}{{product.product_image}}" style="height:50vh;"alt="#">
            <div class="button">
                <a href="" value={{product.id}} class="btn add-cart"><i class="lni lni-cart"></i> Add to Cart</a>
            </div>
        </div>
        <div class="product-info">
            <span class="category">{{product.category}}</span>
            <h4 class="title">
                <a href="{% url 'mainpage:single' slug=product.product_slug %}">{{product.product_name}}</a>
            </h4>
            <ul class="review">
                <li><i class="fa fa-star"></i></li>
                <li><i class="fa fa-star"></i></li>
                <li><i class="fa fa-star"></i></li>
                <li><i class="fa fa-star"></i></li>
                <li><i class="fa fa-star"></i></li>
                <li><span>5.0 Review(s)</span></li>
            </ul>
            <div class="price">
                <span>KES {{product.product_price}}</span>
            </div>
        </div>
    </div>
    <!-- End Single Product -->
</div>
                    {% endfor %}                    
                </div>
                
                <!-- Pagination Start -->
                {%if products.has_other_pages%}

                <div class="col-md-12" style="margin-top: 20px;">
                    <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-center">
                            
                            {% if products.has_previous %}
                                <li class="page-item ">
                            <a class="page-link" href="?page={{products.previous_page_number}}" tabindex="-1">Previous</a>
                            </li>
                            {% else %}
                            <li class="page-item disabled">
                            <a class="page-link" href="" tabindex="-1">Previous</a>
                            </li>
                            {% endif %}
                                {% for i in products.paginator.page_range %}
                                    {% if products.number == i %}
                                        <li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>        
                                    {% else %}
                                    <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                                    {% endif %}
                                {% endfor %}
                                {% if products.has_next %}
                                    <li class="page-item">
                                <a class="page-link" href="?page={{products.next_page_number}}">Next</a>
                            </li>    
                                {% else %}
                                <li class="page-item disabled" >
                                <a class="page-link" href="">Next</a>
                            </li>
                                {% endif %}
                            
                        </ul>
                    </nav>
                </div>
                {%endif%}
                <!-- Pagination Start -->
            </div>           
            
            <!-- Side Bar Start -->
            
            <!-- Side Bar End -->
        </div>
    </div>
</div>
{% endblock content %}  

templates/mainpage/home.html
{% extends "base/base.html" %}
{% load static%}
{%block title%}Home{%endblock%}
{% block content %}


<div class="main_slider" style="background-image:url({% static 'project-290-P9xpYfUpoZI-unsplash.jpg' %});">
<div class="container fill_hight">
    <div class="row align-items-center fill_hight">
        <div class="col">
            <div class="main_slider_content">
                <h6>Spring/summer collections</h6>
                <h1>Get upto 30%of on new arrivals</h1>
                <div class="red_button shop_now_button"><a href="{% url 'mainpage:allproducts'%}">Shop now</a></div>
            </div>
        </div>
    </div>
</div>
</div>
<div class="new_arrivals">
    <h2>new arrivals</h2>
</div>
        <!-- Banner -->
    <!-- Start Hero Area -->
    <section class="hero-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-12 custom-padding-right">
                    <div class="slider-head">
                        <!-- Start Hero Slider -->
                        <div class="hero-slider">
                            <!-- Start Single Slider -->
                            {% for newproduct in new_products %}
                            
                            
                            <div class="single-slider"
                                style="background-image: url({{MEDIA_URL}}{{newproduct.product_image}});">
                                <div class="content">
                                    <h2><span>No restocking fee </span>
                                        {{newproduct.product_name}}
                                    </h2>
                                    <p style="color:white;text-transform:capitalize;s">{{newproduct.product_description}}</p>
                                    <h3><span>Now Only</span> Ksh {{newproduct.product_price}}</h3>
                                    <div class="button">
                                        <a href="{%url 'mainpage:single' slug=newproduct.product_slug %}" class="btn">Shop Now</a>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                            <!-- End Single Slider -->
                            <!-- Start Single Slider -->
                            
                            
                            <!-- End Single Slider -->
                        </div>
                        <!-- End Hero Slider -->
                    </div>
                </div>
                <div class="col-lg-4 col-12">
                    <div class="row">
                        <div class="col-lg-12 col-md-6 col-12 md-custom-padding">
                            <!-- Start Small Banner -->
                            <div class="hero-small-banner"
                                style="background-image: url({% static 'andre-hunter-RPKdvPcYAUo-unsplash.jpg' %});">
                                <div class="content">
                                    <h2>
                                        <span>New line required</span>
                                        iPhone 12 Pro Max
                                    </h2>
                                    <h3>ksh 1259.99</h3>
                                </div>
                            </div>
                            <!-- End Small Banner -->
                        </div>
                        <div class="col-lg-12 col-md-6 col-12">
                            <!-- Start Small Banner -->
                            <div class="hero-small-banner style2">
                                <div class="content">
                                    <h2>Weekly Sale!</h2>
                                    <p>Saving up to 50% off all online store items this week.</p>
                                    <div class="button">
                                        <a class="btn" href="product-grids.html">Shop Now</a>
                                    </div>
                                </div>
                            </div>
                            <!-- Start Small Banner -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

        <!-- New Arrivals -->
        <section class ="feature-products">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 text-center feature-title">
                        <h2>FEATURED PRODUCTS</h2>
                        <a class="feature-active" href="#">BEST SELLER</a> | <a href="#">NEW ARRIVAL</a> | <a href="#">MOST WANTED</a> 
                    </div>

                </div>
            </div>           
            </section>
  <!-- Card -->
  <div class="container">
    <div class="row" >
    {% for product in products%}
    <div class="col-lg-3 col-md-6 col-12" >
            <!-- Start Single Product -->
            <div class="single-product">
                <div class="product-image">
                    <img src="{{MEDIA_URL}}{{product.product_image}}" style="height:350px;" alt="#">
                    <div class="button">
                        <a href=""  id="{{product.id}}" value="{{product.id}}" class="btn add-cart"><i class="lni lni-cart"></i> Add to Cart</a>
                    </div>
                </div>
                <div class="product-info">
                    <span class="category">{{product.category}}</span>
                    <h4 class="title">
                        <a href="{% url 'mainpage:single' slug=product.product_slug %}">{{product.product_name}}</a>
                    </h4>
                    <ul class="review">
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><span>5.0 Review(s)</span></li>
                    </ul>
                    <div class="price">
                        <span>KES {{product.product_price}} </span>
                    </div>
                </div>
            </div>
            <!-- End Single Product -->
        </div>
    {%endfor%}
        
        
        
        
        
        
        
    </div>
</div>
    <div class="more_div">
        <a href="{%url 'mainpage:allproducts' %}" class="more">More Products</a>
    </div>
    


        <!-- Deal of the week -->

        <div id="hot-deal" class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<div class="col-md-12">
						<div class="hot-deal">
							<ul class="hot-deal-countdown">
								<li>
									<div>
										<h3>02</h3>
										<span>Days</span>
									</div>
								</li>
								<li>
									<div>
										<h3>10</h3>
										<span>Hours</span>
									</div>
								</li>
								<li>
									<div>
										<h3>34</h3>
										<span>Mins</span>
									</div>
								</li>
								<li>
									<div>
										<h3>60</h3>
										<span>Secs</span>
									</div>
								</li>
							</ul>
							<h2 class="text-uppercase">hot deal this week</h2>
							<p>New Collection Up to 50% OFF</p>
							<a class="primary-btn cta-btn" href="#">Shop now</a>
						</div>
					</div>
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>

        <!-- Benefit -->

        <section class="shipping-info">
            <div class="container">
                <ul>
                    <!-- Free Shipping -->
                    <li>
                        <div class="media-icon">
                            <i class="lni lni-delivery"></i>
                        </div>
                        <div class="media-body">
                            <h5>Free Shipping</h5>
                            <span>On orders Ksh 5000</span>
                        </div>
                    </li>
                    <!-- Money Return -->
                    <li>
                        <div class="media-icon">
                            <i class="lni lni-support"></i>
                        </div>
                        <div class="media-body">
                            <h5>24/7 Support.</h5>
                            <span>Live Chat Or Call.</span>
                        </div>
                    </li>
                    <!-- Support 24/7 -->
                    <li>
                        <div class="media-icon">
                            <i class="lni lni-credit-cards"></i>
                        </div>
                        <div class="media-body">
                            <h5>Online Payment.</h5>
                            <span>Secure Payment.  </span>
                        </div>
                    </li>
                    <!-- Safe Payment -->
                    <li>
                        <div class="media-icon">
                            <i class="lni lni-reload"></i>
                        </div>
                        <div class="media-body">
                            <h5>Easy Return.</h5>
                            <span>Hassle Free Shopping.</span>
                        </div>
                    </li>
                </ul>
            </div>
        </section>
        <script>
        
            $(document).on('click','.add-cart',function(e){
               
                e.preventDefault();
                
                $.ajax({
                    type:'POST',
                    url: '{% url "basket:basket_add" %}',
                    data:{
                        productid:$(this).attr('value'),
                        csrfmiddlewaretoken: "{{csrf_token}}",
                        action:'post'
                    
                },
                success:function(json){
                    $("#checkout_items").text(json.test)
                    
                },
                error: function(xhr,errmsg,err){}
            });  
                             
            })
        </script>
{% endblock  %}    

templates/mainpage/review.html
{% extends 'base/base.html' %}

{% block title %}
    Review
{% endblock title %} 
{% block content %}
    <div class=" review-modal" id="exampleModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Leave a Review</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="review-name">Your Name</label>
                                <input class="form-control" type="text" id="review-name" required>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="review-email">Your Email</label>
                                <input class="form-control" type="email" id="review-email" required>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="review-subject">Subject</label>
                                <input class="form-control" type="text" id="review-subject" required>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="review-rating">Rating</label>
                                <select class="form-control" id="review-rating">
                                    <option>5 Stars</option>
                                    <option>4 Stars</option>
                                    <option>3 Stars</option>
                                    <option>2 Stars</option>
                                    <option>1 Star</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="review-message">Review</label>
                        <textarea class="form-control" id="review-message" rows="8" required></textarea>
                    </div>
                </div>
                <div class="modal-footer button">
                    <button type="button" class="btn">Submit Review</button>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}